In [203]:
import numpy as np

# Step 1: Set print options

In [204]:
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

# Step 2: Load the raw data

In [205]:
raw_data_np = np.genfromtxt("loan-data.csv", delimiter = ';', skip_header = 1, autostrip = True,encoding = "cp855")

In [206]:
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

# Step 3: Check missing data

In [207]:
np.isnan(raw_data_np).sum()

88005

# Step 4: Temporary fill and mean values

In [208]:
temporary_fill = np.nanmax(raw_data_np) + 1

In [209]:
temporary_mean = np.nanmean(raw_data_np, axis = 0)

/var/folders/1k/26p0wvvn3pq_5gdg1nyk14340000gn/T/ipykernel_16697/3589640931.py:1: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np, axis = 0)


In [210]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [211]:
temporary_stats = np.array([np.nanmin(raw_data_np,axis=0),
                            temporary_mean,np.nanmax(raw_data_np, axis = 0)])

/var/folders/1k/26p0wvvn3pq_5gdg1nyk14340000gn/T/ipykernel_16697/2016062449.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np,axis=0),
/var/folders/1k/26p0wvvn3pq_5gdg1nyk14340000gn/T/ipykernel_16697/2016062449.py:2: RuntimeWarning: All-NaN slice encountered
  temporary_mean,np.nanmax(raw_data_np, axis = 0)])


In [212]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [213]:
np.argwhere(np.isnan(temporary_mean)) == True

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

# Step 6: Split the dataset

In [214]:
columns_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [215]:
columns_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

# Load the string and numeric columns separately

In [216]:
loan_data_strings = np.genfromtxt("loan-data.csv",
delimiter = ';',
skip_header = 1,
autostrip = True,
usecols = columns_strings, dtype = str,encoding =
"cp855")

In [217]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [218]:
loan_data_numeric = np.genfromtxt("loan-data.csv",
delimiter = ';',
autostrip = True, skip_header = 1,
usecols = columns_numeric, filling_values =
temporary_fill,encoding = "cp855")

In [219]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

# Step 7: Load headers

In [220]:
header_full = np.genfromtxt("loan-data.csv",delimiter = ';',autostrip = True,skip_footer = raw_data_np.shape[0],
                            dtype = str,encoding = "cp855") 

In [221]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [222]:
header_strings, header_numeric = header_full[columns_strings], header_full[columns_numeric]

# Step 8: Creating Checkpoints

In [223]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [224]:
checkpoint_test = checkpoint("checkpoint-test", header_strings, loan_data_strings)

In [225]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [226]:
np.array_equal(checkpoint_test['data'], loan_data_strings)

True

# Step 9: Manipulating String Columns

Issue Date Handling

In [227]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [228]:
header_strings[0] = "issue_date"

In [229]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [230]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

Strip year 

In [231]:
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0], "-15")
loan_data_strings[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [232]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

Map month to numbers

In [233]:
for i in range(13):
        loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                          i,
                                          loan_data_strings[:,0])

In [234]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [235]:
loan_data_strings[:,0]

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

# Loan Status Handling

In [236]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [237]:
status_bad = np.array(['','Charged Off','Default','Late (31-120 days)'])

In [238]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1], status_bad),0,1)

In [239]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [240]:
loan_data_strings[:,1]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

# Term Handling
Remove ' months' text and convert empty terms to 60

In [241]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [242]:
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2], " months")
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [243]:
header_strings[2] = "term_months"

In [244]:
np.unique(loan_data_strings[:,2])

array(['', '36', '60'], dtype='<U69')

In [245]:
loan_data_strings[:, 2] = np.where(loan_data_strings[:, 2] == '', '60', loan_data_strings[:, 2])

filling missing values with 60 as default assumption 

# Grade/Subgrade/Verification/URL/State address   Assignment 

# Grade and Subgrade 
- 3 and 4th columns

In [246]:
np.unique(loan_data_strings[:, 3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [247]:
np.unique(loan_data_strings[:, 4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

when having category and subcategory - drop  one of it appropriately - which provide more info 

In [248]:
Grades= np.array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'])

In [249]:
Subgrades = np.array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'])

In [250]:
Grades = np.array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'])

for i in range(len(Grades)):
    loan_data_strings[:, 3] = np.where(loan_data_strings[:, 3] == Grades[i], i, loan_data_strings[:, 3])


In [251]:
print(loan_data_strings[:,3])

['3' '1' '2' ... '1' '4' '1']


In [252]:
np.unique(loan_data_strings[:, 3])

array(['0', '1', '2', '3', '4', '5', '6', '7'], dtype='<U69')

In [253]:
loan_data_strings[:, 3] = loan_data_strings[:, 3].astype(int)
loan_data_strings[:, 3]

array(['3', '1', '2', ..., '1', '4', '1'], dtype='<U69')

In [254]:

unique_grades, grade_counts = np.unique(loan_data_strings[:, 3], return_counts=True)
print("Grades and their counts :")
for grade, count in zip(unique_grades, grade_counts):
    print(f"Grade {grade}: {count}")


Grades and their counts :
Grade 0: 515
Grade 1: 1632
Grade 2: 2606
Grade 3: 2766
Grade 4: 1389
Grade 5: 816
Grade 6: 236
Grade 7: 40


How loan grading and subgrading works ? -> google 

when stuck with data how it work ?
1. know the data - learn what it is
2. understand data - look at the headers 
3. then work on it 


In [255]:
loan_data_strings[:, 4] = np.where(loan_data_strings[:, 4] == '', '00', loan_data_strings[:, 4])
#loan_data_strings[:, 3] = np.chararray.strip(loan_data_strings[:, 3])
loan_data_strings[:, 4] = np.chararray.strip(loan_data_strings[:, 4])
loan_data_strings[:, 4] = np.char.replace(loan_data_strings[:, 4], 'A', '1')
loan_data_strings[:, 4] = np.char.replace(loan_data_strings[:, 4], 'B', '2')
loan_data_strings[:, 4] = np.char.replace(loan_data_strings[:, 4], 'C', '3')
loan_data_strings[:, 4] = np.char.replace(loan_data_strings[:, 4], 'D', '4')
loan_data_strings[:, 4] = np.char.replace(loan_data_strings[:, 4], 'E', '5')
loan_data_strings[:, 4] = np.char.replace(loan_data_strings[:, 4], 'F', '6')
loan_data_strings[:, 4] = np.char.replace(loan_data_strings[:, 4], 'G', '7')
loan_data_strings[:, 4] = np.char.replace(loan_data_strings[:, 4], 'H', '8')


In [256]:
np.unique(loan_data_strings[:, 4] )

array(['00', '11', '12', '13', '14', '15', '21', '22', '23', '24', '25', '31', '32', '33', '34',
       '35', '41', '42', '43', '44', '45', '51', '52', '53', '54', '55', '61', '62', '63', '64',
       '65', '71', '72', '73', '74', '75'], dtype='<U69')

# Verification Status

In [257]:
np.unique(loan_data_strings[:, 5])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [258]:

loan_data_strings[:, 5] = np.where(
    loan_data_strings[:, 5] == 'Not Verified' , 0,
    np.where(np.isin(loan_data_strings[:, 5], ['Source Verified', 'Verified']), 1, 2)
)

loan_data_strings[:,5]

array(['1', '1', '1', ..., '1', '1', '2'], dtype='<U69')

In [259]:
np.unique(loan_data_strings[:, 5])

array(['0', '1', '2'], dtype='<U69')

# URL - remove entirely if unused (assuming index 6)


urls are all same except the loan id , and its already having different column 


In [260]:
loan_data_strings = np.delete(loan_data_strings, 6, axis=1)
header_strings = np.delete(header_strings, 6)

# State Address


In [261]:
states = np.unique(loan_data_strings[:, 6])
states

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [262]:
states, state_count = np.unique(loan_data_strings[:,6],return_counts= True)

In [263]:
states_count_sorted =  np.argsort(-state_count)
states_count_sorted

array([ 5, 33, 42, 10,  0, 13, 30, 11, 37, 34, 21, 26, 44, 19,  4, 46, 18,  6, 23, 22, 14, 47,  7,
       41, 32,  2, 17, 36, 39, 16, 15, 35, 43,  3, 24, 29, 31, 48, 12, 38, 25,  9,  8, 49,  1, 28,
       40, 45, 27, 20])

In [264]:
states[states_count_sorted], state_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [265]:
for i in range(50):
        loan_data_strings[:,6] = np.where(loan_data_strings[:,6] == states[i],
                                          i,
                                          loan_data_strings[:,6])

In [270]:
loan_data_strings[:,6] = np.where(loan_data_strings[:,6] == '', 0 , loan_data_strings[:,6])

In [266]:
loan_data_strings[:,6]

array(['5', '33', '37', ..., '5', '34', '13'], dtype='<U69')

In [ ]:
states_west = np.array([ ])
states_east = np.array([ ])
states_north = np.array([ ])
states_south = np.array([ ])


# Convert all string columns to numeric


In [267]:
loan_data_strings = loan_data_strings.astype(float)

In [268]:
loan_data_strings

array([[ 5.,  1., 36., ..., 33.,  1.,  5.],
       [ 0.,  1., 36., ..., 15.,  1., 33.],
       [ 9.,  1., 36., ..., 25.,  1., 37.],
       ...,
       [ 6.,  1., 36., ..., 15.,  1.,  5.],
       [ 4.,  1., 36., ..., 42.,  1., 34.],
       [12.,  1., 36., ..., 14.,  2., 13.]])

In [269]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

unique counts ?
nan count -> np.isnan(array).sum
groupby 


In [ ]:
temporary_fill
.sum 


varian

currency exchange 

load file 

exchage rate 

from usd to eur 


hstack -> combine 2 columns and  add new column
reshape 
header handling 



In [ ]:
currency exchange 


for i in col_dollar :
     loan_numeric  = np.hstack
     