### Week 10 - Home work

# Instructions
You need to finish all the sections and the points mentioned in each section.

# Section-1 
You need to finish all the given points in a given section:

       Update/Upgrade the NumPy package to the latest version
       Install/Upgrade another package (e.g. Pandas)
       Import NumPy as np
       Use the np.array() function to create an array variable - array_1
       E.g:
        array([[ 10,  15],
               [ 17, 100]])   
   


In [115]:
import numpy as np

np_1SD = np.array([100,110,120,130, 140])
np_1SD

print("array_1:\n", np_1SD)

array_1:
 [100 110 120 130 140]


In [116]:
np_2SD = np.array([[200,300,400,500,600], [430,540,650,760,870], [110,220,330,440,550]])
np_2SD

array([[200, 300, 400, 500, 600],
       [430, 540, 650, 760, 870],
       [110, 220, 330, 440, 550]])

In [117]:
np_3SD = np.array([[[100,200,300,400,500], [110,210,310,401,510]], [[110,120,130,140,150], [510,520,530,540,500]]])
np_3SD

array([[[100, 200, 300, 400, 500],
        [110, 210, 310, 401, 510]],

       [[110, 120, 130, 140, 150],
        [510, 520, 530, 540, 500]]])

# Section-2
    * Generate 4 arrays of size 8
     * 1st Array empty "empty"
     * 2nd array full of  0s
     * 3rd array full of 1s
     * Last array full of 2s
    * Generate 4 more arrays. This time, they should be 2 by 4 arrays.
        * An empty array with the same shape as np_1SD. 
        * An 2-D array of 0s with the same shape as array_2D.
        * A 3-D array of 1s with the same shappe as array_3D.
        * A 3-D array of 2s with the same shape as array_3D.

In [118]:
empty_array = np.empty(8)  # Creates an array of uninitialized values
zeros_array = np.zeros(8)  # Creates an array of 8 zeros
ones_array = np.ones(8)   # Creates an array of 8 ones
twos_array = np.full(8, 2)  # Creates an array of 8 twos

In [119]:
print("Empty array:", empty_array)
print("Zeros array:", zeros_array)
print("Ones array:", ones_array)
print("Twos array:", twos_array)

Empty array: [0.01230661 0.19078228 0.1979822  0.20131642 0.09701997 0.21148643 0.08837214 0.00073395]
Zeros array: [0. 0. 0. 0. 0. 0. 0. 0.]
Ones array: [1. 1. 1. 1. 1. 1. 1. 1.]
Twos array: [2 2 2 2 2 2 2 2]


In [120]:
empty_like_array = np.empty_like(np_1SD) # Empty array with same shape as array_1 (can get filled with garbages)
zeros_2d_array = np.zeros((2, 4))  # 2x4 array of zeros 
ones_3d_array = np.ones_like(np_3SD)  # Array of ones with same shape as array_3
twos_3d_array = np.full_like(np_3SD, 2)  # Array of twos with same shape as array_3

print("\nEmpty like array:", empty_like_array)
print("2D Zeros array:\n", zeros_2d_array)
print("3D Ones array:\n", ones_3d_array)
print("3D Twos array:\n", twos_3d_array)


Empty like array: [0 0 0 0 0]
2D Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
3D Ones array:
 [[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]
3D Twos array:
 [[[2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]]]


# Section -3 
#### Using np.arange() function, solve following
      Generate array from 0 to 40, excluding 40. 
      Generate Array 0 to 40, including 40. 
      Generate integers from 35 to 50, including 50. 
      Generate where 5-th integers from 35 to 50, including 50. 


In [121]:
array_excluding_40 = np.arange(0, 40)
print("array_excluding 40:", array_excluding_40)

array_including_40 = np.arange(0, 41) 
print("array_including_40:", array_including_40)

array_c = np.arange(35, 51)
print("Array c(35 to 50, including 50):", array_c)

array_d = np.arange(35, 51, 5) #(start,stop,step)
print("Array d(Every 5th integer from 35 to 50):", array_d)

array_excluding 40: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
array_including_40: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
Array c(35 to 50, including 50): [35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Array d(Every 5th integer from 35 to 50): [35 40 45 50]


# Section 4
Generate the random value using numpy functions such as .random()

    Use the probability to generate the single event
    Array size of 8 with the probabilities of 8 events. 
    Array of 4 by 8 2 dimensional array with the probabilities of 40 events.  

In [122]:
np.set_printoptions(suppress = True, linewidth = 150)

#   Single random event (between 0 and 1)
single_event = np.random.rand()
print("Single event:", single_event)

Single event: 0.02961438285205431


In [123]:
#   Array of size 8 with probabilities  unNORMALISED - not mutually exclusive
number_of_event  = 8
probabilities_unnormalised = np.random.rand(number_of_event)
print(f"probabilities_unnormalized  of array size {number_of_event}:", probabilities_unnormalised)

#   Array of size 8 with probabilities (must sum to 1) - NORMLISED - Mutually Exclusive and Exhaustive Events
probabilities_normalised = np.random.rand(8)
probabilities_normalised /= probabilities_normalised.sum()  # Normalize to sum to 1
print(f"Probabilities normalised of array size {number_of_event}:", probabilities_normalised)

probabilities_unnormalized  of array size 8: [0.00339255 0.40492221 0.00024239 0.95308682 0.60321752 0.42615884 0.0807506  0.34396895]
Probabilities normalised of array size 8: [0.01929208 0.05992153 0.20854551 0.08126482 0.24460708 0.14542151 0.0919551  0.14899237]


In [128]:
#   Array of size 40 with probabilities  unNORMALISED - not mutually exclusive
number_of_event  = 40 
probabilities_unnormalised = np.random.rand(number_of_event)
print(f"Probabilities unnormalised of array size {number_of_event}", probabilities_unnormalised)

#   Array of size 40 with probabilities (must sum to 1) - NORMLISED - Mutually Exclusive and Exhaustive Events
probabilities_normalised = np.random.rand(40)
probabilities_normalised /= probabilities_normalised.sum()  # Normalize to sum to 1
print(f"Probabilities normalised of array size {number_of_event}", probabilities_normalised)

Probabilities unnormalised of array size 40 [0.87469335 0.1403592  0.92949114 0.93078713 0.95719998 0.56785971 0.44215676 0.17845003 0.66700302 0.3623822  0.02244564 0.23787726 0.76757882
 0.68775778 0.44238053 0.71571644 0.54549369 0.23360524 0.9802578  0.64550392 0.50563562 0.58128226 0.85412236 0.7950527  0.00319106 0.11011398
 0.83650012 0.80752916 0.1096389  0.93453471 0.9223898  0.47571892 0.40015899 0.65187491 0.15050546 0.81379189 0.84625811 0.27047179 0.6314482
 0.27807213]
Probabilities normalised of array size 40 [0.01201966 0.01828576 0.01453385 0.04346054 0.03706352 0.03343032 0.04077999 0.04530193 0.0147345  0.00540783 0.01330801 0.03793934 0.04322995
 0.03488847 0.01024122 0.00132808 0.03443603 0.03686133 0.03015439 0.03202337 0.01644899 0.02461491 0.01036346 0.04390419 0.00122029 0.01270673
 0.03853506 0.00549552 0.02243427 0.00011828 0.02719333 0.01036161 0.03191089 0.00918004 0.02320344 0.02750115 0.04308373 0.03182849 0.04248927
 0.03797826]


In [141]:
chose_random_indices = np.random.choice(number_of_event, size=32, replace=False)
print(f"picked {len(chose_random_indices)} event's indices out of 40")

picked 32 event's indices out of 40


In [143]:
prob_4X8_chose_from_40 = probabilities_unnormalised[chose_random_indices]
event_matrix = prob_4X8_chose_from_40.reshape(4, 8)
event_matrix

array([[0.87469335, 0.17845003, 0.27047179, 0.23360524, 0.23787726, 0.84625811, 0.1403592 , 0.81379189],
       [0.50563562, 0.65187491, 0.80752916, 0.85412236, 0.27807213, 0.9802578 , 0.15050546, 0.7950527 ],
       [0.66700302, 0.9223898 , 0.3623822 , 0.92949114, 0.68775778, 0.64550392, 0.95719998, 0.71571644],
       [0.44238053, 0.83650012, 0.93078713, 0.6314482 , 0.58128226, 0.56785971, 0.44215676, 0.47571892]])

In [124]:
#   4x8 array of probabilities (each row must sum to 1)
probabilities_4x8 = np.random.rand(4, 8)
probabilities_4x8 /= probabilities_4x8.sum(axis=1, keepdims=True)  # Normalize rows
print("Probabilities (4x8):\n", probabilities_4x8)

Probabilities (4x8):
 [[0.04694997 0.23151298 0.20327008 0.10206341 0.02719772 0.03792356 0.23870055 0.11238173]
 [0.20886248 0.17214584 0.01360887 0.0431513  0.1465445  0.03806305 0.18841658 0.18920738]
 [0.00085361 0.00232154 0.25221366 0.25268741 0.11955869 0.10835409 0.09122738 0.17278362]
 [0.24833989 0.1157931  0.17234911 0.01387324 0.22741712 0.02291968 0.14351252 0.05579534]]


# Section 5
    Import the file and display it contents. You can use loadtxt(). You can use the file creditor-total-price.csv
    Import the file and display it contents. You can use np.genfromtxt(). You can use the file creditor-total-price.csv
        Set the data type to strings. 
        Skip the first row of the dataset. 
        Skip the last 15 rows of the dataset. 
        Only pull data from the 2nd, 3rd and 5th columns. 


Hint: By default np.loadtxt() asusmes all the values will be numeric, so it crashes when it encounters text data. We can bypass this by specifying the datatype to NumPy strings when importing.

In [52]:
#   Import with genfromtxt()
try:
    data_loadtxt = np.loadtxt("creditor.csv", delimiter=",", dtype=str)
    print("Data from loadtxt():\n", data_loadtxt)
except FileNotFoundError:
    print("Error: creditor.csv not found (loadtxt)")


#   Import with genfromtxt()
try:
    data_genfromtxt = np.genfromtxt("creditor.csv", delimiter=",", dtype=str, skip_header=1, skip_footer=15, usecols=(1, 2, 4))
    print("\nData from genfromtxt():\n", data_genfromtxt)
except FileNotFoundError:
    print("Error: creditor.csv not found (genfromtxt)")

Error: creditor.csv not found (loadtxt)
Error: creditor.csv not found (genfromtxt)


In [54]:
try:
    data_loadtxt = np.loadtxt("creditors-LT.csv", delimiter=",", dtype=str)
    print("Data from loadtxt():\n", data_loadtxt)
except FileNotFoundError:
    print("Error: creditor-LT.csv not found (loadtxt)")

#   Import with genfromtxt()
try:
    data_genfromtxt = np.genfromtxt("creditors-LT.csv", delimiter=",", dtype=str, skip_header=1, skip_footer=15, usecols=(1, 2, 4))
    print("\nData from genfromtxt():\n", data_genfromtxt)
except FileNotFoundError:
    print("Error: creditors-LT.csv not found (genfromtxt)")

Data from loadtxt():
 [['LoanID' 'StringID' 'LProduct' ... 'Address' 'Area' 'TotalPrice']
 ['1' 'uid_1' 'LProduct B' ... 'Address 2' 'Area 2' '16600']
 ['2' 'uid_2' 'LProduct B' ... 'Address 3' '' '16600']
 ...
 ['1041' 'uid_1041' 'LProduct B' ... 'Address 23' 'Area 4' '16600']
 ['1042' 'uid_1042' 'LProduct C' ... 'Address 52' 'Area 6' '15600']
 ['1043' 'uid_1043' 'LProduct B' ... 'Address 142' 'Area 6' '16600']]

Data from genfromtxt():
 [['uid_1' 'LProduct B' 'Address 2']
 ['uid_2' 'LProduct B' 'Address 3']
 ['uid_3' 'LProduct C' 'Address 5']
 ...
 ['uid_1026' 'LProduct C' 'Address 203']
 ['uid_1027' 'LProduct B' 'Address 6']
 ['uid_1028' 'LProduct D' 'Address 265']]


# Section 6 
    Slice the first column of the np_2SD array
    array([200, 430, 110])
    Slice the last column of the np_2SD  array
    array([600, 870, 550])
    Slice the second row of the np_2SD array
    array([430, 540, 650, 760, 870])
    Slice the last two columns of the np_2SD row of the np_2SD array
    array([760, 870])
    Slice the 2-nd row of the np_2SD array excluding the last two columns
    array([430, 540, 650])
    Slice everything excluding the first row and last column of the np_2SD array
    array([[430, 540, 650, 760],
           [110, 220, 330, 440]])
    Slice the 1st, 3rd and 5th columns of the np_3SD array
    array([[ 1, 11],
           [11, 51]])
    Slice every other column of both matrices in the np_3SD array
    array([[[ 10,  30,  50],
            [110, 310, 510]],
    
           [[110, 130, 150],
            [510, 530,  50]]])
    Use conditional slicing to check if the individual elements of each array satisfy a given condition on np_1SD(e.g. greater than 8)
    array([False,  True,  True,  True,  True])
    Add a second condition and disaply which individual elements satisfy both np_1SD , np_2SD and np_3SD (e.g. greater than 10 and odd)



In [60]:
np_2SD

array([[200, 300, 400, 500, 600],
       [430, 540, 650, 760, 870],
       [110, 220, 330, 440, 550]])

 Slice the first column of the np_2SD array
    array([200, 430, 110])

In [61]:
#   Slice the first column of array_2
first_column = np_2SD[:,0]
print("First column:\n", first_column)

First column:
 [200 430 110]


 Slice the last column of the np_2SD  array
    array([600, 870, 550])

In [57]:
#   Slice the last column of np_2SD
last_column = np_2SD[:, -1]
print("\nLast column:\n", last_column)


Last column:
 [600 870 550]


Slice the second row of the np_2SD array
    array([430, 540, 650, 760, 870])

In [70]:
#   Slice the second row of array_2
second_column = np_2SD[1:2,]
print("Second row:\n", second_column)

Second row:
 [[430 540 650 760 870]]


In [71]:
#   Slice the last two columns of the second row of np_2SD
last_two_second_row = np_2SD[1, -2:]
print("\nLast two of second row:\n", last_two_second_row)


Last two of second row:
 [760 870]


In [72]:
#   Slice the second row of np_2SD excluding the last two columns
second_row_except_last_two = np_2SD[1, :-2]
print("\nSecond row except last two:\n", second_row_except_last_two)



Second row except last two:
 [430 540 650]


In [74]:
#   Slice everything excluding the first row and last column of np_2SD
sliced_2d = np_2SD[1:, :-1]
print("\nSliced 2D:\n", sliced_2d)


Sliced 2D:
 [[430 540 650 760]
 [110 220 330 440]]


In [77]:
np_3SD

array([[[100, 200, 300, 400, 500],
        [110, 210, 310, 401, 510]],

       [[110, 120, 130, 140, 150],
        [510, 520, 530, 540, 500]]])

In [78]:
#   Slice the 1st, 3rd, and 5th columns of the np_3SD array
sliced_3d = np_3SD[:, :, [0, 2, 4]]
print("\nSliced 3D:\n", sliced_3d)


Sliced 3D:
 [[[100 300 500]
  [110 310 510]]

 [[110 130 150]
  [510 530 500]]]


In [83]:
#   Slice every other column of both matrices in the np_3SD array
sliced_3d_every_other = np_3SD[:, :, ::2]
print("\nSliced 3D every other:\n", sliced_3d_every_other)


Sliced 3D every other:
 [[[100 300 500]
  [110 310 510]]

 [[110 130 150]
  [510 530 500]]]


In [85]:
np_1SD

array([100, 110, 120, 130, 140])

In [88]:
#   Conditional slicing on np_1SD (greater than 100)
condition_1sd = np_1SD > 100
print("\nCondition on np_1SD (>8):\n", condition_1sd)



Condition on np_1SD (>8):
 [False  True  True  True  True]


In [91]:
#   Conditional slicing on np_1SD, np_2SD, and np_3SD (greater than 10 and odd)
condition_1sd_both = (np_1SD > 10) & (np_1SD % 2 != 0)
print("\nnp_1SD condition (>10 and odd):\n", condition_1sd_both)


np_1SD condition (>10 and odd):
 [False False False False False]


In [92]:
condition_2sd_both = (np_2SD > 10) & (np_2SD % 2 != 0)
print("\nnp_2SD condition (>10 and odd):\n", condition_2sd_both)


np_2SD condition (>10 and odd):
 [[False False False False False]
 [False False False False False]
 [False False False False False]]


In [93]:
condition_3sd_both = (np_3SD > 10) & (np_3SD % 2 != 0)
print("\nnp_3SD condition (>10 and odd):\n", condition_3sd_both)


np_3SD condition (>10 and odd):
 [[[False False False False False]
  [False False False  True False]]

 [[False False False False False]
  [False False False False False]]]
